development:
  adapter: postgresql
  encoding: unicode
  database: rahm_chicago_development
  pool: 5
  username: rahm
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: rahm_chicago_test
  pool: 5
  username: rahm
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: rahm_production
  pool: 5
  username: rahm_chicago
  password: 
