# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a33975ddf6c6c059f993c20d3c1f5f54ba86d07762a010c497ec9f1f8083d18152a679753ace90dea8088ac5d973bd6e6689ddecd0336068261f5d326f9522cc

test:
  secret_key_base: b97c6bcba23b6cf57c902580fc0447b80a39c77d057f2ca14ae1540f6d67fe5f5c2bf8b7db6c43024d60d8975e30234f468df043b2ee0b946f009cdbc128e49a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
